---
name: Bazel files linter
on:
  workflow_call:
jobs:
  formatting-check:
    name: Run buildifier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run buildifier
        uses: jbajic/buildifier@v1