---
name: Run clang-format Linter
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: jidicula/clang-format-action@69a5d76975736458f550bda2ae5b2505799eec88 # latest
        with:
          clang-format-version: '18'
