---
name: Run clang-format Linter
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          extensions: h,cc
          clangFormatVersion: 16.0.3
