---
name: Run clang-format Linter
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: jidicula/clang-format-action@4dacb6087962f49cedccf872a80c610db1e0e02a # latest
        with:
          clang-format-version: '18'
