---
name: License header check
on:
  workflow_call:
jobs:
  license-check:
    name: Run license check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.5.0
